---
creation_rules:
  # kubernetes secrets
  - path_regex: apps/.+\.sops\.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - age1haxzj5xhxtpag457wwykd4alk7x0cfdzc0gcfgltlvuh7zfywveqz53gjl # secrets-operator-key
          - age1au3v6ztudtm6cchlwga8ws9ujt8r9zj7vwlfs0dc6rycp98jhq2sqw9tkq
stores:
  yaml:
    indent: 2
