---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-apps
spec:
  project: default
  source:
    repoURL: https://github.com/giraffacorp/k8s_core.git
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
